name: Linux Build
on:
  push:
    paths-ignore:
      - '.github/test-build.yaml'
    branches: [ main ]
  workflow_dispatch:
defaults:
  run:
    working-directory: ./
env:
  USE_HARD_LINKS: false
  MIGRATIONS_DIR: /tmp/.migrate
  ASSET_PREFIX: '.'
  npm_config_yes: true
  NEXT_PUBLIC_ENGINES: 1
  MIGRATIONS_ID_TYPE_SQL: bigint
  MIGRATIONS_ID_TYPE_GQL: bigint
  MIGRATIONS_HASURA_PATH: localhost:8080
  MIGRATIONS_HASURA_SSL: 0
  MIGRATIONS_HASURA_SECRET: myadminsecretkey
  NEXT_PUBLIC_DEEPLINKS_SERVER: http://localhost:3007
  NEXT_PUBLIC_GQL_PATH: localhost:3006/gql
  NEXT_PUBLIC_GQL_SSL: 0
  DEEPLINKS_HASURA_PATH: localhost:8080
  DEEPLINKS_HASURA_SSL: 0
  MIGRATIONS_DEEPLINKS_APP_URL: http://host.docker.internal:3007
  MIGRATIONS_DEEPLINKS_URL: http://host.docker.internal:3006
  JWT_SECRET: '{"type":"HS256","key":"3EK6FD+o0+c7tzBNVfjpMkNDi2yARAAKzQlk8O2IKoxQu4nF7EdAh8s3TwpHwrdWT6R"}'
  DOCKER: 1
jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install dependencies
      run: npm clean-install
    - name: Build Android
      run: npm run build-android
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
    - name: Build APK
      run: |
        cd android
        ./gradlew --version
        ./gradlew assembleRelease
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: deep-memo-android.apk
        path: android/app/build/outputs/apk/release/app-release-unsigned.apk