name: Build And Publish

on: 
  workflow_dispatch:

jobs:
  build-and-publish:
    uses: ./.github/workflows/build-and-publish-reusable-workflow.yml
    with:
      app-name: deep-case
      install-electron-dependencies-command: cd electron && npm ci && git clone https://github.com/deep-foundation/deeplinks.git && cp deeplinks/imports/engine.ts ./src/engine.ts && npx rimraf -I deeplinks
