name: Npm Build

on:
  paths-ignore:
    - '.github/test-build.yaml'
  pull_request:
    types: [opened, reopened, edited, synchronize]
  workflow_dispatch:

jobs:
  main:
    uses: deep-foundation/workflows/.github/workflows/npm-build.yml@main